//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aueProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class METTER_DATA
    {
        public int ID { get; set; }
        public Nullable<double> U12 { get; set; }
        public Nullable<double> U23 { get; set; }
        public Nullable<double> U31 { get; set; }
        public Nullable<double> I1 { get; set; }
        public Nullable<double> I2 { get; set; }
        public Nullable<double> I3 { get; set; }
        public Nullable<double> P1 { get; set; }
        public Nullable<double> P2 { get; set; }
        public Nullable<double> P3 { get; set; }
        public Nullable<double> FREQUENCY { get; set; }
        public Nullable<double> AVolt { get; set; }
        public Nullable<double> ACurrent { get; set; }
        public Nullable<double> Consumpiton { get; set; }
        public Nullable<System.DateTime> TimeLog { get; set; }
    }
}
